### PR TITLE
Improve performance of the process method 

### PR DESCRIPTION
**Pull request by kurtymckurt**

### CODE REVIEW

**Comment by kurtymckurt** [comment]
Added updating the mongo cache store to the 8.1 api.

**Comment by kurtymckurt** [comment]
Wrote a jmh benchmark test. 
https://github.com/kurtymckurt/infinispan-cachestore-mongodb-benchmark/blob/master/test/src/main/java/org/sample/MyBenchmark.java

Below are the results comparing the new version vs the previous.

8.1.2.Final

Result "testMethod":
  27.943 ±(99.9%) 0.272 ops/s [Average]
  (min, avg, max) = (25.899, 27.943, 28.712), stdev = 0.549
  CI (99.9%): [27.671, 28.215] (assumes normal distribution)


Run complete. Total time: 00:02:23

Benchmark                Mode  Cnt   Score   Error  Units
MyBenchmark.testMethod  thrpt   50  27.943 ± 0.272  ops/s


6.0.2.Final

Result "testMethod":
  3.526 ±(99.9%) 0.126 ops/s [Average]
  (min, avg, max) = (2.983, 3.526, 3.809), stdev = 0.255
  CI (99.9%): [3.400, 3.652] (assumes normal distribution)


Run complete. Total time: 00:02:36

Benchmark                Mode  Cnt  Score   Error  Units
MyBenchmark.testMethod  thrpt   50  3.526 ± 0.126  ops/s

**Comment by gustavonalle** [comment]
Hi @kurtymckurt, nice improvement!
There is just a config related test failure in https://travis-ci.org/infinispan/infinispan-cachestore-mongodb/builds/112806527, could you take a look?

**Comment by kurtymckurt** [comment]
@gustavonalle  I believe I fixed that test.  Sorry about that.

**Comment by gustavonalle** [comment]
@kurtymckurt fixed, but unfortunately the latest commits introduced other failures

**Comment by kurtymckurt** [comment]
Yeah, I added a stop method to clean up the MongoClient connections for the jmh test and that causes problems with the other tests.  I added a proper startup for it now.

**Comment by gustavonalle** [comment]
Integrated, thanks @kurtymckurt !

**Pull request closed without merging**
